### ISSUE TITLE
Create release v2.0.1

### ISSUE THREAD

**Issue by francoiscrouzet** [archaiodata/thacer#108]
## Todo for all releases

- [x] Set version in this ticket title (e.g. `Create release 2.0.1`)

- [x] Create commit for version in **_dev_**
(The following tasks are done here https://github.com/archaiodata/thacer/edit/dev/vue-thacer/package.json)
    - Update version in `package.json`, but don't commit yet
    - YOU MUST NAME THE COMMIT `vx.x.x`. For instance `v2.0.1`
    - You can add the url of this ticket to the description
    - Commit (directly to the dev branch.)

- [x]  Create commit for version in **_main_**
     - Go to https://github.com/archaiodata/thacer/pulls, click `new pull request`, 
     - Specify that dev will be merged into main : `base : main <-- compare : dev`
     - Click "create pull request"
     - YOU MUST NAME THE PR `vx.x.x`. e.g. `v2.0.1`
     - You can complete the url of this ticket in the text area
     - Click "create pull request",
     - Go to the pull request, Squash and merge

### Do devops things
- [x] locally, on your machine, fetch and pull last version of main 
- [x] `npm run build` locally, on main
    - [x] Optional : copy paste the output of the build in this ticket, so as to be able to follow the build size.
- [x] upload dist to server
- [x] if the release contains change in the api folder, update the api part too on server

## Todo for this specific release
- [x] If we are satisfied with this procedure de mise en production, create an issue template 

## Other infos
(Optional)

**Comment by AlZorba** [comment]
```
vite v4.1.4 building for production...
✓ 182 modules transformed.
dist/index.html                        1.93 kB
dist/assets/ThaCER-1e078ba5.svg       17.55 kB
dist/assets/TheBiblio-54c505a3.css     0.15 kB │ gzip:  0.12 kB
dist/assets/index-b27e12b0.css         0.16 kB │ gzip:  0.14 kB
dist/assets/TheMap-a7cc3d5e.css        1.91 kB │ gzip:  0.77 kB
dist/assets/utils-18956604.js          0.19 kB │ gzip:  0.18 kB │ map:     0.62 kB
dist/assets/NotFound404-7736794b.js    0.44 kB │ gzip:  0.34 kB │ map:     0.82 kB
dist/assets/TheBiblio-b85cc31e.js      2.53 kB │ gzip:  1.19 kB │ map:     5.61 kB
dist/assets/TheMap-82a43496.js        11.62 kB │ gzip:  4.46 kB │ map:    41.50 kB
dist/assets/TheCeramic-e2548770.js    75.49 kB │ gzip: 22.09 kB │ map:   238.86 kB
dist/assets/index-e7f767d3.js        184.04 kB │ gzip: 65.05 kB │ map: 1,320.45 kB
PS C:\web\vue-thacer\thacer\vue-thacer> 
```
