### ISSUE TITLE
Create release 3.0.0

### ISSUE THREAD

**Issue by francoiscrouzet** [archaiodata/thacer#110]
## Todo for all releases

- [x] Set version in this ticket title (e.g. `Create release 2.0.1`)

- [ ] Create commit for version in **_dev_**
(The following tasks are done here https://github.com/archaiodata/thacer/edit/dev/vue-thacer/package.json)
    - Update version in `package.json`, but don't commit yet
    - YOU MUST NAME THE COMMIT `vx.x.x`. For instance `v2.0.1`
    - You can add the url of this ticket to the description
    - Commit (directly to the dev branch.)

- [ ]  Create commit for version in **_main_**
     - Go to https://github.com/archaiodata/thacer/pulls, click `new pull request`, 
     - Specify that dev will be merged into main : `base : main <-- compare : dev`
     - Click "create pull request"
     - YOU MUST NAME THE PR `vx.x.x`. e.g. `v2.0.1`
     - You can complete the url of this ticket in the text area
     - Click "create pull request",
     - Go to the pull request, Squash and merge

### Do devops things
- [x] locally, on your machine, fetch and pull last version of main 
- [x] `npm run build` locally, on main
    - [ ] Optional : copy paste the output of the build in this ticket, so as to be able to follow the build size.
- [x] upload dist to server
- [ ] if the release contains change in the api folder, update the api part too on server

## Todo for this specific release
- [ ] If we are satisfied with this procedure de mise en production, create an issue template 

## Other infos
(Optional)
