### ISSUE TITLE
Create Release v3.1.0

### ISSUE THREAD

**Issue by francoiscrouzet** [archaiodata/thacer#125]
## Todo for all releases

- [x] Set version in this ticket title (e.g. `Create release 3.0.1`)

- [x] Create PR for version in **_dev_**

    - Edit the version number in `package.json`, here : https://github.com/archaiodata/thacer/edit/dev/vue-thacer/package.json
    - Create a COMMIT, named `vx.x.x`. For instance `v3.0.1`
    - Create the PR, named `vx.x.x`. For instance `v3.0.1`
    - Verify the name again (`vx.x.x`), before doing a squash and Merge of the PR
    
    
     
- [x]  Create backup/version branches
     - go to https://github.com/archaiodata/thacer/branches
     - Create new branch with  name : `vx.x.x.`, source : `dev`

### Do devops things
- [x] locally, on your machine, fetch and pull the branch with the last version, who has the commit `vx.x.x`
- [x] `npm run build` locally, on main
    - [x] Optional : copy paste the output of the build in this ticket, so as to be able to follow the build size.
- [x] upload dist to server
- [x] if the release contains change in the api folder, update the api part too on server

## Todo for this specific release
- [ ] If we are satisfied with this procedure de mise en production, create an issue template 

## Other infos
(Optional)

**Comment by francoiscrouzet** [comment]
@AlZorba voila, je veux bien que tu verifies. Ca me parait pas mal, et super rapide pour faire une mep, c'est bien je pense

**Comment by francoiscrouzet** [comment]
@tillrudnick FYI

**Comment by AlZorba** [comment]
PS C:\web\vue-thacer\thacer\vue-thacer> npm run build

> vue-thacer@3.1.0 build
> vite build

vite v4.1.4 building for production...
✓ 190 modules transformed.
dist/index.html                        1.35 kB
dist/assets/ThaCER-1e078ba5.svg       17.55 kB
dist/assets/TheBiblio-c97eb74e.css     0.15 kB │ gzip:  0.12 kB
dist/assets/index-cd47d211.css         0.16 kB │ gzip:  0.14 kB
dist/assets/TheMap-16369b5c.css       19.31 kB │ gzip:  7.27 kB
dist/assets/utils-687ef725.js          0.19 kB │ gzip:  0.18 kB │ map:     0.62 kB
dist/assets/NotFound404-4d120be5.js    0.44 kB │ gzip:  0.34 kB │ map:     0.82 kB
dist/assets/TheBiblio-ab54015b.js      3.00 kB │ gzip:  1.36 kB │ map:     6.61 kB
dist/assets/TheCeramic-10309efe.js    75.52 kB │ gzip: 22.18 kB │ map:   239.06 kB
dist/assets/index-c363b2d0.js        183.96 kB │ gzip: 65.05 kB │ map: 1,320.48 kB
dist/assets/TheMap-6787f481.js       195.04 kB │ gzip: 56.12 kB │ map:   790.19 kB
