### ISSUE TITLE
Create release vx.x.x

### ISSUE THREAD

**Issue by francoiscrouzet** [archaiodata/thacer#134]
## Todo for all releases

- [ ] Set version in this ticket title (e.g. `Create release 3.0.1`)

- [ ] Create PR for version in **_dev_**

    - Edit the version number in `package.json`, here : https://github.com/archaiodata/thacer/edit/dev/vue-thacer/package.json
    - Create a COMMIT, named `vx.x.x`. For instance `v3.0.1`
    - Create the PR, named `vx.x.x`. For instance `v3.0.1`
    - Verify the name again (`vx.x.x`), before doing a squash and Merge of the PR
    
    
     
- [ ]  Create backup/version branches
     - go to https://github.com/archaiodata/thacer/branches
     - Create new branch with  name : `vx.x.x.`, source : `dev`

### Do devops things
- [ ] locally, on your machine, fetch and pull the branch with the last version, who has the commit `vx.x.x`
- [ ] `npm run build` locally, on main
    - [ ] Optional : copy paste the output of the build in this ticket, so as to be able to follow the build size.
- [ ] upload dist to server
- [ ] if the release contains change in the api folder, update the api part too on server

## Todo for this specific release
- [ ] If we are satisfied with this procedure de mise en production, create an issue template 

## Other infos
(Optional)
