### ISSUE TITLE
Create release 2.0.0

### ISSUE THREAD

**Issue by francoiscrouzet** [archaiodata/thacer#82]
## Todo for all releases

- [x] Set version in this ticket title (e.g. `Create release 2.0.1`)

- [x] Create commit for version in **_dev_**
(The following tasks are done here https://github.com/archaiodata/thacer/edit/dev/vue-thacer/package.json)
    - Update version in `package.json`, but don't commit yet
    - YOU MUST NAME THE COMMIT `vx.x.x`. For instance `v2.0.1`
    - You can add the url of this ticket to the description
    - Commit (directly to the dev branch.)

- [ ]  Create commit for version in **_main_**
     - Go to https://github.com/archaiodata/thacer/pulls, click `new pull request`, 
     - Specify that dev will be merged into main : `base : main <-- compare : dev`
     - Click "create pull request"
     - YOU MUST NAME THE PR `vx.x.x`. e.g. `v2.0.1`
     - You can complete the url of this ticket in the text area
     - Click "create pull request",
     - Go to the pull request, Squash and merge

### Do devops things
- [ ] locally, on your machine, fetch and pull last version of main 
- [ ] `npm run build` locally, on main
    - [ ] Optional : copy paste the output of the build in this ticket, so as to be able to follow the build size.
- [ ] upload dist to server
- [ ] if the release contains change in the api folder, update the api part too on server

## Todo for this specific release
- [ ] If we are satisfied with this procedure de mise en production, create an issue template 

## Other infos
(Optional)

**Comment by francoiscrouzet** [comment]
@AlZorba je propose un truc dans le genre pour les mises en production

**Comment by francoiscrouzet** [comment]
> @AlZorba je propose un truc dans le genre pour les mises en production On pourra faire ensemble la premiere? Je propose de mettre le build (dist folder) sur git, comme ça on peut suivre la taille etc. Mais bon, pas vraiment necesaire. Mais pourquoi pas Je montre aussi ça à Till prochainement

Je me rends conpte que pour une grosse mise en prod, c'est ok, mais pour un petit fix rapide, genre un seul commit à mettre en prod, c'est un peu lourd. A voir comment simplifier

**Comment by francoiscrouzet** [comment]
@AlZorba deployment ticket is ready to be used for the first time !
@tillrudnick FYI

**Comment by AlZorba** [comment]
```
vite v4.1.4 building for production...
✓ 182 modules transformed.
dist/index.html                        1.93 kB
dist/assets/ThaCER-1e078ba5.svg       17.55 kB
dist/assets/TheBiblio-54c505a3.css     0.15 kB │ gzip:  0.12 kB
dist/assets/index-1666ba73.css         0.16 kB │ gzip:  0.14 kB
dist/assets/TheMap-a7cc3d5e.css        1.91 kB │ gzip:  0.77 kB
dist/assets/utils-9762a3fc.js          0.19 kB │ gzip:  0.18 kB │ map:     0.62 kBdist/assets/NotFound404-8e7a59db.js    0.44 kB │ gzip:  0.34 kB │ map:     0.82 kBdist/assets/TheBiblio-cf581a61.js      2.53 kB │ gzip:  1.19 kB │ map:     5.61 kBdist/assets/TheMap-64e588f4.js        11.62 kB │ gzip:  4.46 kB │ map:    41.48 kBdist/assets/TheCeramic-9ac1d04a.js    75.49 kB │ gzip: 22.09 kB │ map:   238.86 kBdist/assets/index-6ff85e57.js        183.64 kB │ gzip: 64.85 kB │ map: 1,319.07 kBPS C:\web\vue-thacer\thacer\vue-thacer>
```
